server:
  port: ${SERVER_PORT:8080}
  ssl:
    enabled: true
    key-store: classpath:localhost.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: springboot

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/project_round?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh}
    username: ${DB_USERNAME:app}
    password: ${DB_PASSWORD:app123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: Asia/Ho_Chi_Minh

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:trungdev234@gmail.com}
    password: ${MAIL_PASSWORD:eoib gctk dhmw gmzr}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  # ===== JWT =====
  jwt:
    issuer: stadium-booking
    secret: ${JWT_SECRET:Zk7nQm9vR2pX6aH1tL8cY4uE0sW3dB5fJ9kP2rT7yN1xV6gH8mC0qL4uS5iA3eD}
    access-minutes: 30
  push:
    vapid:
      public-key: BARRnwqaSb921r4qoxVEBS7Al3u3FZ5fonNDBULevuh2Q4WssKNmjix9sbPPsLHOn1Qr7j5l9q75W4QC0Xa8xcQ
      private-key: gOcGtTzcmT7_ZSe9FfOJCFS4yD79JH10i_dB9XbN1s8
      subject: mailto:admin@projectround.local

  # ===== REFRESH TOKEN / COOKIE =====
  refresh:
    days: ${REFRESH_DAYS:7}
    cookie-name: ${REFRESH_COOKIE_NAME:refresh_token}
    cookie-path: ${REFRESH_COOKIE_PATH:/auth}
    secure: true
    same-site: None

  # ===== OTP =====
  otp:
    minutes: ${OTP_MINUTES:10}
    resend-seconds: ${OTP_RESEND_SECONDS:30}

  # ===== BOOTSTRAP ADMIN =====
  bootstrap:
    admin:
      email: ${BOOTSTRAP_ADMIN_EMAIL:admin@gmail.com}
      password: ${BOOTSTRAP_ADMIN_PASSWORD:Admin@123456}
      full-name: ${BOOTSTRAP_ADMIN_NAME:System Admin}
