server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/project_round?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: app
    password: app123

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

  jackson:
    time-zone: Asia/Ho_Chi_Minh
